# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [87]:
import numpy as np
from icecream import ic 

res = np.random.randint(low=0, high=20, size=4*7).reshape((4,7))    # не понял как чделоать float
ic(res)

max_el = np.max(res)
min_el = np.min(res)

normed_res = (res - min_el) / (max_el-min_el)
ic(normed_res)

ic(1.0 in normed_res)
ic(0.0 in normed_res)

ic| res: array([[ 6,  5,  2,  9,  6,  0,  8],
                [17,  7,  0, 19,  9, 11,  3],
                [11, 10,  9,  5, 16,  4,  1],
                [ 1,  7, 14,  2,  4, 14,  9]])
ic| normed_res: array([[0.31578947, 0.26315789, 0.10526316, 0.47368421, 0.31578947,
                        0.        , 0.42105263],
                       [0.89473684, 0.36842105, 0.        , 1.        , 0.47368421,
                        0.57894737, 0.15789474],
                       [0.57894737, 0.52631579, 0.47368421, 0.26315789, 0.84210526,
                        0.21052632, 0.05263158],
                       [0.05263158, 0.36842105, 0.73684211, 0.10526316, 0.21052632,
                        0.73684211, 0.47368421]])
ic| 1.0 in normed_res: True
ic| 0.0 in normed_res: True


True

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [88]:
two_darr = np.random.randint(low=0, high=10, size=8*10).reshape((8,10))
ic(two_darr)

dict_sum_one_darr = {sum(one_dim_arr): idx for idx, one_dim_arr in enumerate(two_darr)}
max_sum = max(dict_sum_one_darr.keys())

idx_max_sum_one_darr = dict_sum_one_darr[max_sum]
ic(f'index={idx_max_sum_one_darr}, one_dim_arr={two_darr[idx_max_sum_one_darr]}, sum={sum(two_darr[idx_max_sum_one_darr])}')



ic| two_darr: array([[5, 6, 9, 0, 4, 7, 8, 6, 0, 5],
                     [0, 5, 5, 8, 5, 5, 5, 0, 3, 9],
                     [7, 6, 0, 0, 0, 9, 2, 1, 4, 6],
                     [5, 6, 1, 1, 8, 0, 1, 0, 1, 7],
                     [6, 1, 7, 2, 0, 5, 3, 2, 6, 1],
                     [8, 6, 9, 1, 2, 5, 6, 0, 6, 2],
                     [5, 6, 2, 1, 3, 1, 6, 3, 3, 5],
                     [0, 2, 1, 8, 2, 7, 2, 0, 9, 0]])
ic| f'index={idx_max_sum_one_darr}, one_dim_arr={two_darr[idx_max_sum_one_darr]}, sum={sum(two_darr[idx_max_sum_one_darr])}': 'index=0, one_dim_arr=[5 6 9 0 4 7 8 6 0 5], sum=50'


'index=0, one_dim_arr=[5 6 9 0 4 7 8 6 0 5], sum=50'

In [89]:
check_sum_list = [sum(one_darr) for one_darr in two_darr]
ic(f'sum_list={check_sum_list}, max_sum={max(check_sum_list)}')

ic| f'sum_list={check_sum_list}, max_sum={max(check_sum_list)}': 'sum_list=[50, 45, 35, 30, 33, 45, 35, 31], max_sum=50'


'sum_list=[50, 45, 35, 30, 33, 45, 35, 31], max_sum=50'

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

![image.png](attachment:image.png)

In [90]:
a= np.array([5,5,5])
b=np.array([2,2,2])


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [91]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [92]:
from pathlib import Path
from csv import reader as csv_reader

cfg_path = Path(__name__).parent / 'data/minutes_n_ingredients.csv'

data_set = np.loadtxt(fname=cfg_path, delimiter=',', skiprows=1, dtype=np.int32)
data_set[:5][:]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [93]:
minutes_arr = data_set[:, 1]
ingrids_arr = data_set[:, 2]

get_one_dim_array_params = lambda arr: {
    'min': np.min(arr), 
    'max': np.max(arr), 
    'mean': np.mean(arr),
    'median': np.median(arr),
}
minutes_arr_params = get_one_dim_array_params(minutes_arr)
ingrids_arr_params = get_one_dim_array_params(ingrids_arr)

ic(minutes_arr_params)
ic(ingrids_arr_params)


ic| minutes_arr_params: {'max': 2147483647, 'mean': 21601.00169, 'median': 40.0, 'min': 0}
ic| ingrids_arr_params: {'max': 39, 'mean': 9.05528, 'median': 9.0, 'min': 1}


{'min': 1, 'max': 39, 'mean': 9.05528, 'median': 9.0}

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [94]:
quantile_minutes = np.quantile(minutes_arr, 0.75)
quantile_minutes 
# пороговое кол-во минут x_a, такое что вероятность P(X < x_a) >= 0.75, 
# где X - случайная величина распределения минут

# то есть с вероятность не менее 75% мы получим рецепт длительностью не более x_a минут
# по заданному распределению

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [95]:
# Для проверки нужно обновить все ячейки !

zero_elements_idxs = np.where(minutes_arr == 0)
print(f'before editing:\n{np.size(np.where(minutes_arr == 0))} zero elements')

data_set[zero_elements_idxs, 1] = 1
minuteprints_arr = data_set[:, 1]

print(f'after editing:\n{np.size(np.where(minutes_arr == 0))} zero elements')



before editing:
479 zero elements
after editing:
0 zero elements


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [96]:
uniques, repeats = np.unique(data_set[:, 1:], return_counts=True, axis=0)
count_uniques = np.shape(uniques)[0]
ic(f'{count_uniques} in {data_set.shape[0]}')


ic| f'{count_uniques} in {data_set.shape[0]}': '4183 in 100000'


'4183 in 100000'

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [97]:
unique_ingrids = np.unique(data_set[:, 2])
ic(f'count unique ingridients combs: {np.shape(unique_ingrids)[0]}')
ic(unique_ingrids)

ic| f'count unique ingridients combs: {np.shape(unique_ingrids)[0]}': 'count unique ingridients combs: 37'
ic| unique_ingrids: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                           18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
                           35, 37, 39])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [98]:
ingrids_arr = data_set[:, 2]
new_data_set_idxs = np.where(ingrids_arr < 6)
lower_than_six_ingrids_data_set = data_set[new_data_set_idxs]
ic(lower_than_six_ingrids_data_set.size)

ic| lower_than_six_ingrids_data_set.size: 51786


51786

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [99]:
ingrids_per_minute = data_set[:, 2] / data_set[:, 1]
ic(ingrids_per_minute)
max_ingrids_per_minute = np.max(ingrids_per_minute)
ic(max_ingrids_per_minute)

ic| ingrids_per_minute: array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
                               0.1       ])
ic| max_ingrids_per_minute: 24.0


24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [100]:
# как не использовать типизированные массивы ?

# dtype = np.dtype([('id', int), ('minutes', int), ('ingrids', int)])
# sorted_dataset = np.array([], dtype=dtype)
# ic(sorted_dataset)
# sorted_dataset = data_set.copy()
# ic(sorted_dataset)

# ic(sorted_dataset)
# sorted_dataset.dtype = [('id', int), ('minutes', int), ('ingrids', int)]      # ['id', int, 'minutes', int, 'ingrids', int]
# sorted_dataset.sort(order='minutes')
# ic(sorted_dataset)

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [101]:
data_set_size = np.shape(data_set)[0]
rand_idxs = np.random.randint(low=0, high=data_set_size, size=10)
ic(data_set[rand_idxs, :])

ic| data_set[rand_idxs, :]: array([[419519,     30,     12],
                                   [316336,    240,      5],
                                   [ 83316,     42,      6],
                                   [366734,     25,      5],
                                   [190517,     35,      5],
                                   [389917,     75,     13],
                                   [397470,     45,     10],
                                   [ 25021,     70,     15],
                                   [137752,     50,      8],
                                   [ 83609,     55,     12]])


array([[419519,     30,     12],
       [316336,    240,      5],
       [ 83316,     42,      6],
       [366734,     25,      5],
       [190517,     35,      5],
       [389917,     75,     13],
       [397470,     45,     10],
       [ 25021,     70,     15],
       [137752,     50,      8],
       [ 83609,     55,     12]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [102]:
lower_than_mean_ingrids_idxs = np.where(ingrids_arr_params['mean'] < ingrids_arr)
ic(f'percent lower than mean ingrids {100*np.shape(lower_than_mean_ingrids_idxs)[1]/data_set_size}%')

ic| f'percent lower than mean ingrids {100*np.shape(lower_than_mean_ingrids_idxs)[1]/data_set_size}%': 'percent lower than mean ingrids 41.198%'


'percent lower than mean ingrids 41.198%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [103]:
lower20_minutes = np.where(minuteprints_arr <= 20)
lower5_ingrids = np.where(minuteprints_arr <= 5)
ic(np.shape(lower20_minutes), np.shape(lower5_ingrids))
simple_recepy_idxs = np.intersect1d(lower20_minutes, lower5_ingrids)
ic(np.shape(simple_recepy_idxs))

is_recepy_simple = np.zeros(data_set_size).reshape(data_set_size,1)
is_recepy_simple[simple_recepy_idxs] = 1

full_dataset = np.concatenate((data_set, is_recepy_simple), axis=1)
ic(full_dataset)

ic| np.shape(lower20_minutes): (1, 26650)
    np.shape(lower5_ingrids): (1, 6343)
ic| np.shape(simple_recepy_idxs): (6343,)
ic| full_dataset: array([[1.27244e+05, 6.00000e+01, 1.60000e+01, 0.00000e+00],
                         [2.38910e+04, 2.50000e+01, 7.00000e+00, 0.00000e+00],
                         [9.47460e+04, 1.00000e+01, 6.00000e+00, 0.00000e+00],
                         ...,
                         [4.98432e+05, 6.50000e+01, 1.50000e+01, 0.00000e+00],
                         [3.70915e+05, 5.00000e+00, 4.00000e+00, 1.00000e+00],
                         [8.19930e+04, 1.40000e+02, 1.40000e+01, 0.00000e+00]])


array([[1.27244e+05, 6.00000e+01, 1.60000e+01, 0.00000e+00],
       [2.38910e+04, 2.50000e+01, 7.00000e+00, 0.00000e+00],
       [9.47460e+04, 1.00000e+01, 6.00000e+00, 0.00000e+00],
       ...,
       [4.98432e+05, 6.50000e+01, 1.50000e+01, 0.00000e+00],
       [3.70915e+05, 5.00000e+00, 4.00000e+00, 1.00000e+00],
       [8.19930e+04, 1.40000e+02, 1.40000e+01, 0.00000e+00]])

13. Выведите процент "простых" рецептов в датасете

In [104]:
ic(f'percent simple recepyes {100*np.shape(simple_recepy_idxs)[0]/data_set_size}%')

ic| f'percent simple recepyes {100*np.shape(simple_recepy_idxs)[0]/data_set_size}%': 'percent simple recepyes 6.343%'


'percent simple recepyes 6.343%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [108]:
three_dim_data_set = np.zeros((3, 1, 3))
short_recepyes_idxs = np.where(minutes_arr < 10)
standart_recepyes_idxs = np.intersect1d(np.where(10 <= minutes_arr), np.where(minutes_arr < 20 ))
long_recepyes_idxs = np.where(minutes_arr >= 20)

three_dim_data_set[0] = short_recepyes_idxs


ValueError: could not broadcast input array from shape (1,7588) into shape (1,3)